### ISSUE TITLE
Use interfaces and pkg/models

### ISSUE THREAD

**Issue by JamolpeAxa** [lsm-dev/license-header-checker#18]
This is more a structure improvement/way of thinking.
You can define the dependencies you need by defining an interface with the methods you are expecting this way you can change the packages dependencies and implementation (also is good for testing you can create Stubs more easy)

example:
process package depends of config, file and header packages you can define an interface of each one and inyect it creating a method that inithialize a process pacakage pointer NewPointer(...interfaces)

This improvement is not really needed due is a library with an specific behavior is more a way of structure and create bigger library dependencies.

nice job!

**Comment by lsm-dev** [comment]
Thanks! As you said it is not really needed for this specific use case but thanks anyway for sharing!
