### ISSUE TITLE
Ignore folders not respected

### ISSUE THREAD

**Issue by ericzon** [lsm-dev/license-header-checker#21]
Other cases seems to work well but trying -i flag with an ignorable folder located in:
/Users/myuser/my-project/other-folder/path/to/**ignorable-folder**

Executing command from: /Users/myuser/my-project/other-folder/path with common flags: 
**-v -a -r**

-i relative-path/to/ignorable-folder **Output** -> "Ignore folders: [relative-path/to/ignorable-folder]"
-i relative-path/to/ignorable-folder/ **Output** -> "Ignore folders: [relative-path/to/ignorable-folder/]"
-i absolute-path/to/ignorable-folder/ **Output** -> "Ignore folders: [absolute-path/to/ignorable-folder/]"

Files in that folder and subfolders are modified.

If I specify some wildcard in the ignore directory (...ignorable-folder/*), flags seems missmatched.

I hope it helps

**O.S:** MacOS Mojave 10.14.3

**Comment by lsm-dev** [comment]
Hi @ericzon ,

Thanks for your feedback!

The -i flag currently accepts a **comma separated** list  of **file/folder names** 
`license-header-checker -i node_modules,docs,myFile.txt`

I will **add the possibility to provide paths** to -i flag asap in the **next release**. Stay tuned!

The wildcard functionality is not planned in the near future (I will make it explicit in the docs). Anyway, I accept PRs ;)
