### ISSUE TITLE
Using -r will remove build tags above license

### ISSUE THREAD

**Issue by irvinlim** [lsm-dev/license-header-checker#31]
Firstly, thanks for the amazing tool!

I have one small issue to report. In source files with a build tag above the license, running the tool with `-r` will accidentally remove those build tags if the license is different.

Example diff after running the tool when I update the license:

```diff
diff --git a/a.go b/a.go
index 3b5f281..e5fdaaa 100644
--- a/a.go
+++ b/a.go
@@ -1,8 +1,5 @@
-//go:build linux
-// +build linux
-
 /*
- * Copyright 2022 <Name>
+ * Copyright 2022 <New Name>
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
diff --git a/hack/boilerplate.go.txt b/hack/boilerplate.go.txt
index 0cfe2ae..696bdd8 100644
--- a/hack/boilerplate.go.txt
+++ b/hack/boilerplate.go.txt
@@ -1,5 +1,5 @@
 /*
- * Copyright 2022 <Name>
+ * Copyright 2022 <New Name>
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
```

**Comment by lsm-dev** [comment]
Hi @irvinlim!

I am glad that you found the tool useful.

Thanks for the feedback, I'll provide a new version soon that will not accidentally remove the build tags when replacing a license.

**Comment by lsm-dev** [comment]
Hi again @irvinlim,

You can now download the new release [v1.3](https://github.com/lsm-dev/license-header-checker/releases/tag/v1.3.0) that does not remove the build tags.

Regards,
Lluis

**Comment by irvinlim** [comment]
Amazing, thanks @lsm-dev for the fix!
